#define QUOTE(...) #__VA_ARGS__

const char JACK_AND_THE_BEANSTALK[4096] = QUOTE(
    Jack, a poor country boy, trades the family cow for a handful of magic beans, which grow into a massive, towering beanstalk reaching up into the clouds. Jack climbs the beanstalk and finds himself in the castle of an unfriendly giant. Jack went inside the house and found the giants wife in the kitchen. Jack said, Could you please give me something to eat? I am so hungry!. The kind wife gave him bread and some milk. While he was eating, the giant came home. The giant senses Jacks presence and cries,
    Fee-fi-fo-fum!
    The giant was very big and looked very fearsome. Jack was terrified and went and hid inside. The giant cried, Fee-fi-fo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, Ill grind his bones to make my bread! The wife said, There is no boy in here! So, the giant ate his food and then went to his room. He took out his sacks of gold coins, counted them and kept them aside. Then he went to sleep. In the night, Jack crept out of his hiding place, took one sack of gold coins and climbed down the beanstalk. At home, he gave the coins to his mother. His mother was very happy and they lived well for sometime.
    Jack climbed the beanstalk and went to the giants house again. Once again, Jack asked the giants wife for food, but while he was eating the giant returned. Jack leapt up in fright and went and hid under the bed. The giant cried, Fee-fifo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, Ill grind his bones to make my bread! The wife said, There is no boy in here! The giant ate his food and went to his room. There, he took out a hen. He shouted, Lay! and the hen laid a golden egg. When the giant fell asleep, Jack took the hen and climbed down the beanstalk. Jacks mother was very happy with him.
    After some days, Jack once again climbed the beanstalk and went to the giants castle. For the third time, Jack met the giants wife and asked for some food. Once again, the giants wife gave him bread and milk. But while Jack was eating, the giant came home. Fee-fi-fo-fum, I smell the blood of an Englishman. Be he alive, or be he dead, Ill grind his bones to make my bread! cried the giant. Dont be silly! There is no boy in here! said his wife.
    The giant had a magical harp that could play beautiful songs. While the giant slept, Jack took the harp and was about to leave. Suddenly, the magic harp cried, Help master! A boy is stealing me! The giant woke up and saw Jack with the harp. Furious, he ran after Jack. But Jack was too fast for him. He ran down the beanstalk and reached home. The giant followed him down. Jack quickly ran inside his house and fetched an axe. He began to chop the beanstalk. The giant fell and died.
    Jack and his mother were now very rich and they lived happily ever after.
    Be he alive, or be he dead, Ill grind his bones to make my bread.
    Outwitting the giant, Jack is able to retrieve many goods from the giant, including a bag of gold, an enchanted goose that lays golden eggs and a magic golden harp that plays and sings by itself. Jack then escapes by chopping down the beanstalk. The giant, who is pursuing him, falls to his death, and Jack and his family prosper.
);
